language: php
php:
  - "5.4"
  - "5.3"
env:
  - DB=mysql
  - DB=pgsql
mysql:
  adapter: mysql2
  database: claroline_test
  username: travis
  encoding: utf8
postgres:
  adapter: postgresql
  database: claroline_test
  username: postgres
before_script: sh ./travis.sh
script: phpunit -c app --testsuite core
