parameters:
    
    claroline.plugin.directory: "%kernel.root_dir%/../src/plugin"
    claroline.plugin.tool_directory: "%claroline.plugin.directory%/tool"
    claroline.plugin.extension_directory: "%claroline.plugin.directory%/extension"
    claroline.plugin.namespaces_config_file: "%kernel.root_dir%/config/plugin/namespaces"
    claroline.plugin.bundles_config_file: "%kernel.root_dir%/config/plugin/bundles"
    claroline.plugin.routing_config_file: "%kernel.root_dir%/config/plugin/routing.yml"
    
services:
    
    claroline.plugin.installer:
        class: Claroline\PluginBundle\Installer\Installer
        arguments:
            - "@claroline.plugin.loader"
            - "@claroline.plugin.validator"
            - "@claroline.plugin.migrator"
            - "@claroline.plugin.recorder"
            - "@kernel"
    
    claroline.plugin.loader:
        class: Claroline\PluginBundle\Installer\Loader
        arguments:
            - tool: %claroline.plugin.tool_directory%
              extension: %claroline.plugin.extension_directory%
              
    claroline.plugin.validator:
        class: Claroline\PluginBundle\Installer\Validator\Validator
        arguments:
            - "@claroline.plugin.common_checker"
            - "@claroline.plugin.tool_checker"
            - "@claroline.plugin.extension_checker"
    
    claroline.plugin.common_checker:
        class: Claroline\PluginBundle\Installer\Validator\Checker\CommonChecker
        arguments:
            - %claroline.plugin.routing_config_file%
            - tool: %claroline.plugin.tool_directory%
              extension: %claroline.plugin.extension_directory%
            - "@symfony.yaml"
            - "@file_locator"
    
    claroline.plugin.extension_checker:
        class: Claroline\PluginBundle\Installer\Validator\Checker\ExtensionChecker
  
    claroline.plugin.tool_checker:
        class: Claroline\PluginBundle\Installer\Validator\Checker\ToolChecker

    claroline.plugin.migrator:
        class: Claroline\PluginBundle\Installer\Migrator
        arguments:
            - "@claroline.install.bundle_migrator"
            
    claroline.plugin.recorder:
        class: Claroline\PluginBundle\Installer\Recorder\Recorder
        arguments:
            - "@claroline.plugin.recorder_configuration_file_writer"
            - "@claroline.plugin.recorder_database_writer"
            
    claroline.plugin.recorder_configuration_file_writer:
        class: Claroline\PluginBundle\Installer\Recorder\Writer\ConfigurationFileWriter
        arguments:
            - %claroline.plugin.namespaces_config_file%
            - %claroline.plugin.bundles_config_file%
            - %claroline.plugin.routing_config_file%
            - "@symfony.yaml"
    
    claroline.plugin.recorder_database_writer:
        class: Claroline\PluginBundle\Installer\Recorder\Writer\DatabaseWriter
        arguments:
            - "@validator"
            - "@doctrine.orm.entity_manager"

    # symfony class used as service argument
    symfony.yaml:
        class: Symfony\Component\Yaml\Yaml
        public: false