parameters:
    claroline.plugin.directory: "%kernel.root_dir%/../src/plugin"
    claroline.plugin.namespaces.config_file: "%kernel.root_dir%/config/plugin/namespaces"
    claroline.plugin.bundles.config_file: "%kernel.root_dir%/config/plugin/bundles"
    claroline.plugin.routing.config_file: "%kernel.root_dir%/config/plugin/routing.yml"

services:
    claroline.plugin.file_handler:
        class: Claroline\PluginBundle\Service\PluginManager\FileHandler
        arguments:
            - %claroline.plugin.namespaces.config_file%
            - %claroline.plugin.bundles.config_file%
            - %claroline.plugin.routing.config_file%
            - "@symfony.yaml"
    claroline.plugin.migrations_handler:
        class: Claroline\PluginBundle\Service\PluginManager\MigrationsHandler
        arguments:
            - "@claroline.install.bundle_migrator"
    claroline.plugin.routing_prefixes:
        class: ArrayObject
        factory_service: claroline.plugin.file_handler
        factory_method: getRegisteredRoutingPrefixes
    claroline.plugin.application_validator:
        class: Claroline\PluginBundle\Service\PluginManager\ApplicationValidator
        public: false
    claroline.plugin.tool_validator:
        class: Claroline\PluginBundle\Service\PluginManager\ToolValidator
        public: false
    claroline.plugin.validator:
        class: Claroline\PluginBundle\Service\PluginManager\Validator
        arguments:
            - %claroline.plugin.directory%
            - "@claroline.plugin.routing_prefixes"
            - "@symfony.yaml.parser"
        calls:
            - [setApplicationValidator, ["@claroline.plugin.application_validator"]]
            - [setToolValidator, ["@claroline.plugin.tool_validator"]]
    claroline.plugin.database_handler:
        class: Claroline\PluginBundle\Service\PluginManager\DatabaseHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@claroline.security.role_manager"
    claroline.plugin.manager:
        class: Claroline\PluginBundle\Service\PluginManager\Manager
        arguments:
            - "@claroline.plugin.validator"
            - "@claroline.plugin.file_handler"
            - "@claroline.plugin.database_handler"
            - "@claroline.plugin.migrations_handler"
            
    # symfony classes used as service arguments
    symfony.yaml.parser:
        class: Symfony\Component\Yaml\Parser
        public: false
    symfony.yaml:
        class: Symfony\Component\Yaml\Yaml
        public: false