services:
    claroline.common.doctrine_load_metadata_subscriber:
        class: Claroline\CommonBundle\Listener\ExtendableListener
        calls:
          - [setContainer, ["@service_container"]] 
          - [setAnnotationReader, ["@annotation_reader"]]
        tags:
            - { name: doctrine.event_subscriber, event: loadClassMetadata, connection: default }