services:
    claroline.common.doctrine_load_metadata_subscriber:
        class: Claroline\CommonBundle\Service\ORM\DynamicInheritance\Listener\ExtendableListener
        calls:
          - [setContainer, ["@service_container"]] 
          - [setAnnotationReader, ["@annotation_reader"]]
        tags:
            - { name: doctrine.event_subscriber, event: loadClassMetadata, connection: default }          
    # controller
    claroline.common.platform_index_controller:
        class: Claroline\CommonBundle\Controller\PlatformIndexController
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@templating.engine.twig"