imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:   %test_database_driver%
        host:     %test_database_host%
        dbname:   %test_database_name%
        user:     %test_database_user%
        password: %test_database_password%
    orm:
        mappings:
            claroline_core_stubs:
                type: annotation
                dir: %kernel.root_dir%/../src/core/Claroline/CoreBundle/Tests/Stub/Entity
                prefix: Claroline\CoreBundle\Tests\Stub\Entity

parameters:
    test.client.class: Claroline\CoreBundle\Testing\TransactionalTestClient
    claroline.install.include_test_migrations: true
    claroline.stub_plugin_directory: %kernel.root_dir%/../src/core/Claroline/CoreBundle/Tests/Stub/plugin
