imports:
    - { resource: security.yml }
    - { resource: local/parameters.yml }

framework:
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator:      { fallback: en }
    default_locale: %locale%
    session:
      cookie_lifetime: 15

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    variables:
        locale: [en, fr]
    filters:
        cssrewrite: ~
        #twig_js:
        #    resource: "%kernel.root_dir%/../vendor/jms/twig-js-bundle/JMS/TwigJsBundle/Resources/config/services.xml"
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false

swiftmailer:
    transport:  %mailer_transport%
    encryption: %mailer_encryption%
    auth_mode:  %mailer_auth_mode%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%

jms_security_extra:
    secure_all_services: false

jms_di_extra:
    locations:
        # set the following option to false and explicitely name
        # the bundles for optimal performance in dev environment
        all_bundles: true
        # bundles: [FooBundle, AcmeBlogBundle]
        directories: ["%kernel.root_dir%/../src"]

stof_doctrine_extensions:
    orm:
        default:
            tree: true   # listeners are not enabled by default
            timestampable: true

parameters:
  security.authentication.listener.anonymous.class: Claroline\CoreBundle\Listener\AnonymousAuthenticationListener