imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:   %test_database_driver%
        host:     %test_database_host%
        dbname:   %test_database_name%
        user:     %test_database_user%
        password: %test_database_password%
    orm:
        mappings:
            claroline_core_stubs:
                type: annotation
                dir: %kernel.root_dir%/../src/core/Claroline/CoreBundle/Tests/Stub/Entity
                prefix: Claroline\CoreBundle\Tests\Stub\Entity

parameters:
    test.client.class: Claroline\CoreBundle\Library\Testing\TransactionalTestClient
    claroline.install.include_test_migrations: true
    claroline.stub_plugin_directory: %kernel.root_dir%/../src/core/Claroline/CoreBundle/Tests/Stub/plugin
    # next line overrides the parameter defined in core config/services/resource.yml
    claroline.files.directory: "%kernel.root_dir%/../test/files"
    claroline.config.platform_handler_class : Claroline\CoreBundle\Library\Testing\PlatformTestConfigurationHandler
    claroline.config.platform_options_files:
        prod: %kernel.root_dir%/config/local/platform_options.yml
        test: %kernel.root_dir%/config/local/platform_test_options.yml