claro_index:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Home:index }

claro_security:
    resource: "@ClarolineCoreBundle/Resources/config/routing/security.yml"

claro_profile:
    resource: "@ClarolineCoreBundle/Resources/config/routing/profile.yml"
    prefix: profile

claro_registration:
    resource: "@ClarolineCoreBundle/Resources/config/routing/registration.yml"
    prefix: register

claro_desktop:
    resource: "@ClarolineCoreBundle/Controller/DesktopController.php"
    prefix: desktop
    type: annotation

claro_desktop_tool_calendar:
    resource: "@ClarolineCoreBundle/Controller/Tool/CalendarController.php"
    prefix: desktop/tool/calendar
    type: annotation

claro_desktop_tool_home:
    resource: "@ClarolineCoreBundle/Controller/Tool/HomeController.php"
    prefix: desktop/tool/home
    type: annotation

claro_desktop_tool_properties:
    resource: "@ClarolineCoreBundle/Controller/Tool/DesktopParametersController.php"
    prefix: desktop/tool/properties
    type: annotation

claro_workspace:
    resource: "@ClarolineCoreBundle/Resources/config/routing/workspace.yml"
    prefix: workspaces

claro_workspace_tool_properties:
    resource: "@ClarolineCoreBundle/Resources/config/routing/workspace_tool_parameters.yml"
    prefix: workspaces/tool/properties

claro_workspace_tool_user:
    resource: "@ClarolineCoreBundle/Resources/config/routing/workspace_tool_user.yml"
    prefix: workspaces/tool/user_management

claro_workspace_tool_group:
    resource: "@ClarolineCoreBundle/Resources/config/routing/workspace_tool_group.yml"
    prefix: workspaces/tool/group_management

claro_workspace_tool_calendar:
    resource: "@ClarolineCoreBundle/Resources/config/routing/workspace_tool_calendar.yml"
    prefix: workspaces/tool/calendar

claro_admin:
    resource: "@ClarolineCoreBundle/Controller/AdministrationController.php"
    prefix: admin
    type: annotation

claro_admin_widget:
    resource: "@ClarolineCoreBundle/Controller/AdministrationWidgetController.php"
    prefix: admin
    type: annotation

claro_resource:
    resource: "@ClarolineCoreBundle/Resources/config/routing/resource.yml"
    prefix: resource

claro_text:
    resource: "@ClarolineCoreBundle/Resources/config/routing/text.yml"
    prefix: text

claro_mail:
    resource: "@ClarolineCoreBundle/Resources/config/routing/mail.yml"
    prefix: mail

claro_message:
    resource: "@ClarolineCoreBundle/Resources/config/routing/message.yml"
    prefix: message

claro_activity:
    resource: "@ClarolineCoreBundle/Controller/ActivityController.php"
    prefix: activity
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

claro_install:
    resource: "@ClarolineCoreBundle/Resources/config/routing/install.yml"
    prefix: install
