claro_core:
    resource: "@ClarolineCoreBundle/Resources/config/routing.yml"

claro_user:
    resource: "@ClarolineUserBundle/Resources/config/routing.yml"




claro_core_security:
    resource: "@ClarolineSecurityBundle/Resources/config/routing.yml"