claro_index:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Home:index }

claro_security:
    resource: "@ClarolineCoreBundle/Resources/config/routing/security.yml"

claro_user:
    resource: "@ClarolineCoreBundle/Resources/config/routing/user.yml"
    prefix: user
    
claro_home:
    resource: "@ClarolineCoreBundle/Resources/config/routing/home.yml"
    prefix: home    

claro_desktop:
    resource: "@ClarolineCoreBundle/Resources/config/routing/desktop.yml"
    prefix: desktop
    
claro_workspace:
    resource: "@ClarolineCoreBundle/Resources/config/routing/workspace.yml"
    prefix: workspace
    
claro_admin:
    resource: "@ClarolineCoreBundle/Resources/config/routing/admin.yml"
    prefix: admin    

claro_file:
    resource: "@ClarolineCoreBundle/Resources/config/routing/file.yml"
    prefix: file    
    
claro_resource:
    resource: "@ClarolineCoreBundle/Resources/config/routing/resource.yml"
    prefix: resource
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"