claro_index:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Home:index }

claro_security:
    resource: "@ClarolineCoreBundle/Resources/config/routing/security.yml"

claro_profile:
    resource: "@ClarolineCoreBundle/Resources/config/routing/profile.yml"
    prefix: profile

claro_registration:
    resource: "@ClarolineCoreBundle/Resources/config/routing/registration.yml"
    prefix: register

claro_home:
    resource: "@ClarolineCoreBundle/Resources/config/routing/home.yml"
    prefix: home

claro_desktop:
    resource: "@ClarolineCoreBundle/Resources/config/routing/desktop.yml"
    prefix: desktop

claro_workspace:
    resource: "@ClarolineCoreBundle/Resources/config/routing/workspace.yml"
    prefix: workspaces

claro_workspace_user:
    resource: "@ClarolineCoreBundle/Resources/config/routing/workspace_user.yml"
    prefix: workspaces

claro_workspace_group:
    resource: "@ClarolineCoreBundle/Resources/config/routing/workspace_group.yml"
    prefix: workspaces

claro_admin:
    resource: "@ClarolineCoreBundle/Resources/config/routing/admin.yml"
    prefix: admin

claro_resource:
    resource: "@ClarolineCoreBundle/Resources/config/routing/resource.yml"
    prefix: resource

claro_text:
    resource: "@ClarolineCoreBundle/Resources/config/routing/text.yml"
    prefix: text

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
claro_install:
    resource: "@ClarolineCoreBundle/Resources/config/routing/install.yml"
    prefix: install