# Assetic controller is disabled until a solution is found for the
# TwigJs translation filter in dev environment. Use assetic:dump
# instead.
#
#_assetic:
#    resource: .
#    type:     assetic

_jasmine:
    resource: "@ClarolineCoreBundle/Controller/JasmineController.php"
    type: annotation

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_main:
    resource: routing.yml