claro_common:
    resource: "@ClarolineCommonBundle/Resources/config/routing.yml"

claro_workspace:
    resource: "@ClarolineWorkspaceBundle/Resources/config/routing.yml"

claro_security:
    resource: "@ClarolineSecurityBundle/Resources/config/routing.yml"