security:
  
    providers:
        user_db:
            entity: { class: Claroline\CoreBundle\Entity\User, property: username }
    
    encoders:
        Claroline\CoreBundle\Entity\User: sha512
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login: ~
            anonymous: ~
            logout: true
    
    access_control:
        - { path: ^/desktop, roles: ROLE_USER }
        - { path: ^/workspace/new, roles: ROLE_WS_CREATOR }
        - { path: ^/workspace, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user/profile, roles: ROLE_USER }
        - { path: ^/resource, roles: ROLE_USER }
        - { path: ^/resource, roles: ROLE_ADMIN }
        - { path: ^/file, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
    
    acl:
        connection: default