security:
  
    providers:
        user_db:
            entity: { class: Claroline\UserBundle\Entity\User, property: username }
    
    encoders:
        Claroline\UserBundle\Entity\User: sha512
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login: ~
            anonymous: ~
            logout: true
    
    role_hierarchy:
         ROLE_ADMIN: ROLE_USER
         ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    access_control:
        - { path: ^/desktop, roles: ROLE_USER }
        - { path: ^/workspaces, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
    
    acl:
        connection: default