security:

    providers:
        user_db:
            entity: { class: Claroline\CoreBundle\Entity\User }

    encoders:
        Claroline\CoreBundle\Entity\User: sha512

    firewalls:
        install:
            pattern: ^/install
            security: false
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login: ~
            anonymous: ~
            logout: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/desktop, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }

    acl:
        connection: default
        voter:
          allow_if_object_identity_unavailable: false

    access_decision_manager:
        allow_if_all_abstain: false