security:

    providers:
        user_db:
            entity: { class: Claroline\UserBundle\Entity\User, property: username }

    encoders:
        Claroline\UserBundle\Entity\User: sha512

    firewalls:  
        main:
            pattern:    ^/
            form_login: ~
            anonymous: ~
            logout: true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN:  ROLE_ADMIN

    access_control:
        # The WDT has to be allowed to anonymous users to avoid requiring the login with the AJAX request
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # AsseticBundle paths used when using the controller for assets
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Always accessible paths
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/claroline_register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.+, role: ROLE_USER }

    acl:
        connection: default