parameters:
    claroline.config.platform_handler_class : Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler
    claroline.config.platform_options_files:
        prod: %kernel.root_dir%/config/local/platform_options.yml

    claroline.install.prod_migrations_directory: Migrations
    claroline.install.test_migrations_directory: Tests/Stub/Migrations
    claroline.install.include_test_migrations: false # see config_test.yml
    claroline.plugin.directory: "%kernel.root_dir%/../src/plugin"
    claroline.plugin.namespaces_config_file: "%kernel.root_dir%/config/local/plugin/namespaces"
    claroline.plugin.bundles_config_file: "%kernel.root_dir%/config/local/plugin/bundles"
    claroline.plugin.routing_config_file: "%kernel.root_dir%/config/local/plugin/routing.yml"

    # next lines are overriden by app config_test.yml in test environment
    claroline.files.directory: "%kernel.root_dir%/../files"
    claroline.thumbnails.directory: "%kernel.root_dir%/../web/thumbnails"

    claroline.workspace_template.directory: "%kernel.root_dir%/../templates/"