services:
  user_repository:
    class:           Claroline\CoreBundle\Repository\UserRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\User

  message_repository:
    class:           Claroline\CoreBundle\Repository\MessageRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Message

  resource_type_repository:
    class:           Claroline\CoreBundle\Repository\ResourceTypeRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Resource\ResourceType

  resource_rights_repository:
    class:           Claroline\CoreBundle\Repository\ResourceRightsRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Resource\ResourceType

  resource_repository:
    class:           Claroline\CoreBundle\Repository\AbstractResourceRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Resource\AbstractResource