claro_security_login:
    pattern: /login
    defaults: { _controller: ClarolineSecurityBundle:Authentication:login }

claro_security_login_check:
    pattern: /login_check

claro_security_logout:
    pattern: /logout