services:
    claroline.security.role_manager:
        class: Claroline\SecurityBundle\Service\RoleManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@validator"
    #controller
    claroline.security.authentication:
        class: Claroline\SecurityBundle\Controller\AuthenticationController
        scope: request
        arguments:
            - "@request"
            - "@templating.engine.twig"