claro_activity_add_resource:
    pattern: /{activityId}/add/resource/{resourceId}
    defaults: { _controller: ClarolineCoreBundle:Activity:addResource }
    options:
      expose: true

claro_activity_remove_resource:
    pattern: /{activityId}/remove/resource/{resourceId}
    defaults: { _controller: ClarolineCoreBundle:Activity:removeResource }
    options:
      expose: true

claro_activity_set_sequence:
    pattern: /{activityId}/set/sequence
    defaults: { _controller: ClarolineCoreBundle:Activity:setSequenceOrder }
    options:
      expose: true

claro_activity_left_menu:
    pattern: /leftmenu/{activityId}
    defaults: { _controller: ClarolineCoreBundle:Activity:renderLeftMenu }
    options:
      expose: true

claro_activity_show_player:
    pattern: /player/{activityId}
    defaults: { _controller: ClarolineCoreBundle:Activity:showPlayer }

claro_activity_setup:
    pattern: /setup/{activityId}
    defaults: { _controller: ClarolineCoreBundle:Activity:showSetUp }

claro_activity_show_instructions:
    pattern: /instructions/{activityId}
    defaults: { _controller: ClarolineCoreBundle:Activity:showInstructions }