claro_admin_index:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Administration:index }
    options:
      expose: true

#users

claro_admin_user_creation_form:
    pattern: /user/create/form
    defaults: { _controller: ClarolineCoreBundle:Administration:userCreationForm }

claro_admin_create_user:
    pattern: /user/create
    defaults: { _controller: ClarolineCoreBundle:Administration:createUser }

claro_admin_delete_user:
    pattern: /user/delete/{userId}
    defaults: { _controller: ClarolineCoreBundle:Administration:deleteUser }

claro_admin_user_list:
    pattern: /user/list
    defaults: { _controller: ClarolineCoreBundle:Administration:userList }

claro_admin_paginated_user_list:
   pattern: /user/paginated/list/{page}/{format}
   defaults: { _controller: ClarolineCoreBundle:Administration:paginatedUserList }
   options:
      expose: true

#groups

claro_admin_group_creation_form:
    pattern: /group/create/form
    defaults: { _controller: ClarolineCoreBundle:Administration:groupCreationForm }

claro_admin_create_group:
    pattern: /group/create
    defaults: { _controller: ClarolineCoreBundle:Administration:createGroup }

claro_admin_group_list:
    pattern: /group/list
    defaults: { _controller: ClarolineCoreBundle:Administration:groupList }

claro_admin_group_user_list:
    pattern: /group/{groupId}
    defaults: { _controller: ClarolineCoreBundle:Administration:groupUserList }

claro_admin_user_list_addable_to_group:
    pattern: /group/add/{groupId}
    defaults: { _controller: ClarolineCoreBundle:Administration:userListAddableToGroup }

claro_admin_add_user_to_group:
    pattern: /group/add/user/{groupId}/{userId}
    defaults: { _controller: ClarolineCoreBundle:Administration:addUserToGroup }

claro_admin_delete_user_from_group:
    pattern: /group/delete/user/{groupId}/{userId}
    defaults: { _controller: ClarolineCoreBundle:Administration:deleteUserFromGroup }

claro_admin_delete_group:
    pattern: /group/delete/{groupId}
    defaults: { _controller: ClarolineCoreBundle:Administration:deleteGroup }

claro_admin_group_settings_form:
   pattern: /group/settings/form/{groupId}
   defaults: { _controller: ClarolineCoreBundle:Administration:groupSettingsForm }

claro_admin_update_group_settings:
   pattern: /group/settings/update/{groupId}
   defaults: { _controller: ClarolineCoreBundle:Administration:updateGroupSettings }

claro_admin_paginated_group_list:
   pattern: /group/paginated/list/{page}/{format}
   defaults: { _controller: ClarolineCoreBundle:Administration:paginatedGroupList }
   options:
      expose: true


#platform

claro_admin_platform_settings_form:
   pattern: /platform/settings/form
   defaults: { _controller: ClarolineCoreBundle:Administration:platformSettingsForm }

claro_admin_update_platform_settings:
   pattern: /platform/settings/update
   defaults: { _controller: ClarolineCoreBundle:Administration:updatePlatformSettings }




