claro_desktop_index:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Desktop:index }

claro_desktop_info:
    pattern: /info
    defaults: { _controller: ClarolineCoreBundle:Desktop:info }

claro_desktop_perso:
    pattern: /perso
    defaults: { _controller: ClarolineCoreBundle:Desktop:perso }

claro_desktop_resources:
    pattern: /resources
    defaults: { _controller: ClarolineCoreBundle:Desktop:resourceManager }
    options:
        expose: true

claro_desktop_widgets:
    pattern: /widgets
    defaults: { _controller: ClarolineCoreBundle:Desktop:widgets }
