claro_desktop_index:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Desktop:index }

claro_desktop_info:
    pattern: /info
    defaults: { _controller: ClarolineCoreBundle:Desktop:info }

claro_desktop_perso:
    pattern: /perso
    defaults: { _controller: ClarolineCoreBundle:Desktop:perso }

claro_desktop_resources:
    pattern: /resources
    defaults: { _controller: ClarolineCoreBundle:Desktop:resourceManager }
    options:
        expose: true

claro_desktop_widgets:
    pattern: /widgets
    defaults: { _controller: ClarolineCoreBundle:Desktop:widgets }

claro_desktop_user_parameters:
    pattern: /user/parameters
    defaults: { _controller: ClarolineCoreBundle:Desktop:desktopUserParameters }

claro_widget_properties:
    pattern: /widget/properties
    defaults: { _controller: ClarolineCoreBundle:Desktop:widgetProperties }

claro_desktop_widget_invertvisible:
    pattern: /config/{displayConfigId}/widget/{widgetId}/invert
    defaults: { _controller: ClarolineCoreBundle:Desktop:invertVisibleUserWidget }
    requirements:
      _method: POST
    options:
      expose: true


