claro_widget_properties:
    pattern: /widget/properties
    defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopWidgetProperties }

claro_desktop_widget_invertvisible:
    pattern: /config/{displayConfigId}/widget/{widgetId}/invertvisible
    defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopInvertVisibleUserWidget }
    requirements:
      _method: POST
    options:
      expose: true

claro_desktop_widget_configuration:
  pattern: widget/{widgetId}/configuration/desktop
  defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopConfigureWidget }
  requirements:
    _method: GET
  options:
    expose: true

claro_tool_properties:
  pattern: /tools
  defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopConfigureTool }

claro_tool_desktop_remove:
  pattern: /remove/tool/{toolId}
  defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopRemoveTool }
  requirements:
      _method: POST
  options:
    expose: true

claro_tool_desktop_remove:
  pattern: /remove/tool/{toolId}
  defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopRemoveTool }
  requirements:
    _method: POST
  options:
    expose: true

claro_tool_desktop_add:
  pattern: /add/tool/{toolId}/position/{position}
  defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopAddTool }
  requirements:
      _method: POST
  options:
    expose: true

claro_tool_desktop_move:
  pattern: /move/tool/{toolId}/position/{position}
  defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopMoveTool }
  requirements:
    _method: POST
  options:
    expose: true
