claro_widget_properties:
    pattern: /widget/properties
    defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopWidgetProperties }

claro_desktop_widget_invertvisible:
    pattern: /config/{displayConfigId}/widget/{widgetId}/invertvisible
    defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopInvertVisibleUserWidget }
    requirements:
      _method: POST
    options:
      expose: true

claro_desktop_widget_configuration:
  pattern: widget/{widgetId}/configuration/desktop
  defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopConfigureWidget }
  requirements:
    _method: GET
  options:
    expose: true

claro_tool_properties:
  pattern: /tool/properties
  defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopConfigureTool }

claro_tool_invert_visibility:
  pattern: /invert/visibility/tool/{toolId}
  defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopInvertToolVisibility }
  requirements:
      _method: POST
  options:
    expose: true

claro_tool_move_up:
  pattern: /move/up/tool/{toolId}
  defaults: { _controller: ClarolineCoreBundle:Tool/Parameters:desktopMoveToolUp }
  requirements:
    _method: POST
  options:
    expose: true
