#todo change route add_to_xxx
ClarolineCoreBundle_directory_add:
    pattern: /add/{id}
    defaults: { _controller: ClarolineCoreBundle:Directory:add, id:null }
    options:
       expose: true    
  
ClarolineCoreBundle_directory_add_to_directory:
    pattern: /show/{id}
    defaults: { _controller: ClarolineCoreBundle:Directory:addToDirectory, id:null }
    options:
       expose: true
    
ClarolineCoreBundle_directory_view:
    pattern: /view/{id}
    defaults: { _controller: ClarolineCoreBundle:Directory:view, id:null }
    
ClarolineCoreBundle_directory_delete:
    pattern: /delete/{id}
    defaults: { _controller: ClarolineCoreBundle:Directory:delete }
    options:
       expose: true
    
ClarolineCoreBundle_directory_form:
    pattern: /form
    defaults: { _controller: ClarolineCoreBundle:Directory:form }
    options:
       expose: true    