claro_checkAdminForm:
    pattern: /step_check3
    defaults: { _controller: 'ClarolineCoreBundle:Install:checkAdminForm' }
    requirements: { _method: post }
claro_checkDbForm:
    pattern: /step_check_2
    defaults: { _controller: 'ClarolineCoreBundle:Install:checkDbForm' }
    requirements: { _method: post }
claro_execute:
    pattern: /execute
    defaults: { _controller: 'ClarolineCoreBundle:Install:execute' }
    requirements: { _method: post }
claro_setup:
    pattern: /
    defaults: { _controller: 'ClarolineCoreBundle:Install:index' }
claro_permission:
    pattern: /permission
    defaults: { _controller: 'ClarolineCoreBundle:Install:permission' }
claro_showAdminForm:
    pattern: /step_3
    defaults: { _controller: 'ClarolineCoreBundle:Install:showAdminForm' }
    requirements: { _method: post }
claro_showDbForm:
    pattern: /step_2/{lg}
    defaults: { _controller: 'ClarolineCoreBundle:Install:showDbForm' }
claro_sucess:
    pattern: /sucess
    defaults: { _controller: 'ClarolineCoreBundle:Install:success' }
    requirements: { _method: post }
claro_summary:
    pattern: /summary
    defaults: { _controller: 'ClarolineCoreBundle:Install:summaryShow' }
