claro_message_delete_from:
    pattern: /delete/from
    defaults: { _controller: 'ClarolineCoreBundle:Message:deleteFromUser' }
    options: { expose: true }
claro_message_delete_to:
    pattern: /delete/to
    defaults: { _controller: 'ClarolineCoreBundle:Message:deleteToUser' }
    options: { expose: true }
claro_message_form:
    pattern: /form
    defaults: { _controller: 'ClarolineCoreBundle:Message:form' }
claro_message_form_for_group:
    pattern: '/form/group/{groupId}'
    defaults: { _controller: 'ClarolineCoreBundle:Message:formForGroup' }
claro_message_list_received:
    pattern: '/list/received/{offset}'
    defaults: { _controller: 'ClarolineCoreBundle:Message:listReceived' }
    options: { expose: true }
claro_message_list_received_layout:
    pattern: /list/received
    defaults: { _controller: 'ClarolineCoreBundle:Message:listReceivedLayout' }
claro_message_list_received_search:
    pattern: '/list/received/search/{search}/offset/{offset}'
    defaults: { _controller: 'ClarolineCoreBundle:Message:listSearchReceived' }
    options: { expose: true }
claro_message_list_removed:
    pattern: '/list/removed/{offset}'
    defaults: { _controller: 'ClarolineCoreBundle:Message:listRemoved' }
    options: { expose: true }
claro_message_list_removed_layout:
    pattern: /list/removed
    defaults: { _controller: 'ClarolineCoreBundle:Message:listRemovedLayout' }
claro_message_list_removed_search:
    pattern: '/list/removed/search/{search}/offset/{offset}'
    defaults: { _controller: 'ClarolineCoreBundle:Message:listRemovedSearch' }
    options: { expose: true }
claro_message_list_sent:
    pattern: '/list/sent/{offset}'
    defaults: { _controller: 'ClarolineCoreBundle:Message:listSent' }
    options: { expose: true }
claro_message_list_sent_layout:
    pattern: /list/sent
    defaults: { _controller: 'ClarolineCoreBundle:Message:listSentLayout' }
claro_message_list_sent_search:
    pattern: '/list/sent/search/{search}/offset/{offset}'
    defaults: { _controller: 'ClarolineCoreBundle:Message:listSearchSent' }
    options: { expose: true }
claro_message_mark_as_read:
    pattern: '/mark_as_read/{userMessageId}'
    defaults: { _controller: 'ClarolineCoreBundle:Message:markAsRead' }
    options: { expose: true }
claro_message_send:
    pattern: '/send/{parentId}'
    defaults: { _controller: 'ClarolineCoreBundle:Message:send', parentId: 0 }
claro_message_show:
    pattern: '/show/{messageId}'
    defaults: { _controller: 'ClarolineCoreBundle:Message:show' }
