claro_resource_creation_form:
    pattern: /form/{resourceType}
    defaults: { _controller: ClarolineCoreBundle:Resource:creationForm }
    options:
        expose: true

claro_resource_create:
    pattern: /create/{resourceType}/{parentId}
    defaults: { _controller: ClarolineCoreBundle:Resource:create }
    options:
        expose: true

claro_resource_delete:
    pattern: /delete
    defaults: { _controller: ClarolineCoreBundle:Resource:delete }
    options:
        expose: true

claro_resource_export:
    pattern: /export
    defaults: { _controller: ClarolineCoreBundle:Resource:export }
    options:
        expose: true

claro_resource_move:
   pattern: /move/{newParentId}
   defaults: { _controller: ClarolineCoreBundle:Resource:move }
   options:
        expose: true

claro_resource_open:
   pattern: /open/{resourceType}/{resourceId}
   defaults: { _controller: ClarolineCoreBundle:Resource:open }
   options:
     expose: true

claro_resource_custom:
    pattern: /custom/{resourceType}/{action}/{resourceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:custom }
    options:
        expose: true

claro_resource_roots:
    pattern: /roots
    defaults: { _controller: ClarolineCoreBundle:Resource:roots }
    options:
        expose: true

claro_resource_root:
    pattern: /root/{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:root }
    options:
        expose: true

claro_resource_children:
    pattern: children/{resourceId}/{resourceTypeId}
    defaults: { _controller: ClarolineCoreBundle:Resource:children, resourceId: 0, resourceTypeId: 0}
    options:
        expose: true

claro_resource_parents:
     pattern: parents/{resourceId}
     defaults: { _controller: ClarolineCoreBundle:Resource:parents }
     options:
        expose: true

claro_resources_list:
    pattern: list/{resourceTypeId}/{rootId}
    defaults: { _controller: ClarolineCoreBundle:Resource:resourceList }
    options:
       expose: true

claro_resource_copy:
    pattern: /copy/{resourceDestinationId}
    defaults: { _controller: ClarolineCoreBundle:Resource:copy }
    options:
        expose: true

claro_resource_filter:
    pattern: /filter
    defaults: { _controller: ClarolineCoreBundle:Resource:filter }
    options:
        expose: true

claro_resource_every_instances:
    pattern: /user/instances/all
    defaults: { _controller: ClarolineCoreBundle:Resource:userEveryInstances }
    options:
        expose: true

claro_resource_form_properties:
    pattern: /properties/form/{resourceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:propertiesForm }

claro_resource_edit_properties:
    pattern: /properties/edit/{resourceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:changeProperties }

claro_resource_create_shortcut:
    pattern: /shortcut/{newParentId}/create
    defaults: { _controller: ClarolineCoreBundle:Resource:createShortcut }
    options:
        expose: true

claro_resource_rename_form:
    pattern: /rename/form/{resourceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:renameForm }
    options:
        expose: true

claro_resource_rename:
    pattern: /rename/{resourceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:rename }
    options:
        expose: true

claro_resource_right_form:
    pattern: /{resourceId}/rights/form
    defaults: { _controller: ClarolineCoreBundle:Resource:rightForm }
    options:
        expose: true

claro_resource_right_edit:
   pattern: /{resourceId}/rights/edit
   defaults: { _controller: ClarolineCoreBundle:Resource:editRights }
   options:
        expose: true
