claro_resource_index:
    pattern: /directory/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:index, id:null}
    
claro_resource_show_form:
    pattern: /form/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:showResourceForm, id:null }
    
claro_resource_view:
    pattern: /view/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:view }
    
claro_resource_delete:
    pattern: /delete/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:delete }
    options:
      expose: true.
      
claro_resource_open:
   pattern: /open/{id}
   defaults: { _controller: ClarolineCoreBundle:Resource:open }
    
claro_resource_JSON_tree:
    pattern: /JSONTree/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:getJSONTree }
    options:
       expose: true
       
claro_resource_fakeroute:
    pattern: tree/JSON
    defaults: { _controller: ClarolineCoreBundle:Resource:index }
    options:
      expose: true
       
claro_resource_JSON_node:
    pattern: tree/JSON/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:getJSONResourceNode }
    options:
      expose: true
      
ClarolineCoreBundle_resource_addToWorkspace:
   pattern: workspace/add/{idResource}/{idWorkspace}
   defaults: { _controller: ClarolineCoreBundle:Resource:addToWorkspace }
   options:
      expose: true
      
ClarolineCoreBundle_resource_removeFromWorkspace:
   pattern: workspace/remove/{idResource}/{idWorkspace}
   defaults: { _controller: ClarolineCoreBundle:Resource:removeFromWorkspace }
   options:
      expose: true 
   
claro_resource_add_resource:
   pattern: /add/{type}/{id}
   defaults: { _controller: ClarolineCoreBundle:Resource:add, id:null }   
   
claro_resource_default_click:
   pattern: /click/{type}/{id}
   defaults: { _controller: ClarolineCoreBundle:Resource:defaultClick }