claro_resource_index:
    pattern: /index
    defaults: { _controller: ClarolineCoreBundle:Resource:index}
    
claro_resource_add_to_directory:
    pattern: /add/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:addToDirectory, id:null }
    
claro_resource_view:
    pattern: /view/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:view }
    
claro_resource_delete:
    pattern: /delete/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:delete }
    
claro_resource_JSON_tree:
    pattern: /JSONTree/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:getJSONTree }
    options:
       expose: true