claro_resource_index:
    pattern: /directory/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:index, id:null}
    
claro_resource_show_form:
    pattern: /form/show/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:showResourceForm, id:null }
    
claro_resource_delete:
    pattern: /delete/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:delete }
    options:
      expose: true
      
claro_resource_open:
   pattern: /open/{id}
   defaults: { _controller: ClarolineCoreBundle:Resource:open }
   options:
      expose: true   
    
claro_resource_JSON_tree:
    pattern: /JSONTree/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:getJSONTree }
    options:
       expose: true
       
claro_resource_JSON_node:
    pattern: tree/JSON/{id}
    defaults: { _controller: ClarolineCoreBundle:Resource:getJSONResourceNode }
    options:
      expose: true
      
claro_resource_move:
   pattern: move/{idChild}/{idParent}
   defaults: { _controller: ClarolineCoreBundle:Resource:moveResource }
   options:
      expose: true
      
claro_resource_add_workspace:
   pattern: workspace/add/{resourceId}/{workspaceId}
   defaults: { _controller: ClarolineCoreBundle:Resource:addToWorkspace }
   options:
      expose: true
      
claro_resource_remove_workspace:
   pattern: workspace/remove/{resourceId}/{workspaceId}
   defaults: { _controller: ClarolineCoreBundle:Resource:removeFromWorkspace }
   options:
      expose: true 
   
claro_resource_add_resource:
   pattern: /add/{type}/{id}
   defaults: { _controller: ClarolineCoreBundle:Resource:add, id:null }  
   options:
      expose: true
   
claro_resource_default_click:
   pattern: /click/{type}/{id}
   defaults: { _controller: ClarolineCoreBundle:Resource:defaultClick, type:null }
   options:
       expose: true
    
   
claro_resource_form_resource:
   pattern: /form/{id}/{type}
   defaults: { _controller: ClarolineCoreBundle:Resource:getForm }
   options:
      expose: true
      
claro_resource_type_resource:
   pattern: /type/all
   defaults: { _controller: ClarolineCoreBundle:Resource:getResourcesType }
   options:
      expose: true