claro_resource_creation_form:
    pattern: /form/{resourceType}
    defaults: { _controller: ClarolineCoreBundle:Resource:creationForm }
    options:
        expose: true

claro_resource_create:
    pattern: /create/{resourceType}/{parentInstanceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:create }
    options:
        expose: true

claro_resource_properties_form:
    pattern: /form/properties/{resourceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:basePropertiesForm }
    options:
        expose: true

claro_resource_properties_update:
    pattern: /update/properties/{instanceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:updateBaseProperties }
    options:
        expose: true

claro_resource_delete:
    pattern: /delete/{instanceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:delete }
    options:
        expose: true

claro_resource_multi_delete:
    pattern: /multidelete
    defaults: { _controller: ClarolineCoreBundle:Resource:multiDelete }
    options:
        expose: true

claro_resource_export:
    pattern: /export/{instanceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:export }
    options:
        expose: true

claro_multi_export:
    pattern: /multiexport
    defaults: { _controller: ClarolineCoreBundle:Resource:multiExport }
    options:
        expose: true

claro_resource_move:
   pattern: /move/{instanceId}/{newParentId}
   defaults: { _controller: ClarolineCoreBundle:Resource:move }
   options:
        expose: true

claro_resource_multimove:
   pattern: /multimove/{newParentId}
   defaults: { _controller: ClarolineCoreBundle:Resource:multimove }
   options:
        expose: true

claro_resource_custom:
    pattern: /custom/{resourceType}/{action}/{resourceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:custom }
    options:
        expose: true

claro_resource_roots:
    pattern: /roots
    defaults: { _controller: ClarolineCoreBundle:Resource:roots }
    options:
        expose: true

claro_resource_root:
    pattern: /root/{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:root }
    options:
        expose: true

claro_resource_children:
    pattern: children/{instanceId}/{resourceTypeId}
    defaults: { _controller: ClarolineCoreBundle:Resource:children, instanceId: 0, resourceTypeId: 0}
    options:
        expose: true

claro_resource_parents:
     pattern: parents/{instanceId}
     defaults: { _controller: ClarolineCoreBundle:Resource:parents }
     options:
        expose: true

claro_resource_types:
    pattern: types
    defaults: { _controller: ClarolineCoreBundle:Resource:resourceTypes }
    options:
        expose: true

claro_resources_list:
    pattern: list/{resourceTypeId}/{rootId}
    defaults: { _controller: ClarolineCoreBundle:Resource:resourceList }
    options:
       expose: true

claro_resource_menus:
    pattern: /menus
    defaults: { _controller: ClarolineCoreBundle:Resource:menus }
    options:
        expose: true

claro_resource_add_workspace:
    pattern: /workspace/add/{instanceId}/{instanceDestinationId}
    defaults: { _controller: ClarolineCoreBundle:Resource:addToWorkspace }
    options:
        expose: true

claro_resource_multi_add_workspace:
    pattern: /workspace/multi/add/{instanceDestinationId}
    defaults: { _controller: ClarolineCoreBundle:Resource:multiAddToWorkspace }
    options:
        expose: true

claro_resource_renders_filter:
    pattern: /filter/renders/{prefix}
    defaults: { _controller: ClarolineCoreBundle:Resource:rendersFilters }
    options:
        expose: true

claro_resource_filter:
    pattern: /filter
    defaults: { _controller: ClarolineCoreBundle:Resource:filter }
    options:
        expose: true

claro_resource_every_instances:
    pattern: /user/instances/all
    defaults: { _controller: ClarolineCoreBundle:Resource:userEveryInstances }
    options:
        expose: true

claro_resource_count_instances:
    pattern: /count/instances
    defaults: { _controller: ClarolineCoreBundle:Resource:countPageInstance }
    options:
        expose: true

claro_resource_paginate_all:
    pattern: /instance/flat/{page}
    defaults: { _controller: ClarolineCoreBundle:Resource:paginatedFlatResource }
    options:
        expose: true