claro_resource_creation_form:
    pattern: /form/{resourceType}
    defaults: { _controller: ClarolineCoreBundle:Resource:creationForm }
    options:
        expose: true

claro_resource_create:
    pattern: /create/{resourceType}/{parentInstanceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:create }
    options:
        expose: true

claro_resource_properties_form:
    pattern: /form/properties/{resourceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:basePropertiesForm }
    options:
        expose: true

claro_resource_properties_update:
    pattern: /update/properties/{instanceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:updateBaseProperties }
    options:
        expose: true

claro_resource_delete:
    pattern: /delete/{instanceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:delete }
    options:
        expose: true

claro_resource_move:
   pattern: move/{instanceId}/{newParentId}
   defaults: { _controller: ClarolineCoreBundle:Resource:move }
   options:
        expose: true

claro_resource_custom:
    pattern: /custom/{resourceType}/{action}/{resourceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:custom }
    options:
        expose: true

claro_resource_roots:
    pattern: /roots
    defaults: { _controller: ClarolineCoreBundle:Resource:roots }
    options:
        expose: true

claro_resource_root:
    pattern: /root/{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:root }
    options:
        expose: true

claro_resource_children:
    pattern: children/{instanceId}
    defaults: { _controller: ClarolineCoreBundle:Resource:children }
    options:
        expose: true

claro_resource_types:
    pattern: types
    defaults: { _controller: ClarolineCoreBundle:Resource:resourceTypes }
    options:
        expose: true

claro_resources_list:
    pattern: list/{resourceTypeId}/{rootId}
    defaults: { _controller: ClarolineCoreBundle:Resource:resourceList }
    options:
        expose: true

claro_resource_menus:
    pattern: /menus
    defaults: { _controller: ClarolineCoreBundle:Resource:menus }
    options:
        expose: true

claro_resource_add_workspace:
    pattern: workspace/add/{instanceId}/{options}/{instanceDestinationId}
    defaults: { _controller: ClarolineCoreBundle:Resource:addToWorkspace }
    options:
        expose: true
        options: ref|copy
