claro_security_login:
    pattern: /login
    defaults: { _controller: claroline.controller.authentication:loginAction }

claro_security_login_check:
    pattern: /login_check

claro_security_logout:
    pattern: /logout