claro_user_registration_form:
    pattern: /register
    defaults: { _controller: claroline.controller.registration:newAction }
    
claro_user_registration_form_submit:
    pattern: /create
    defaults: { _controller: claroline.controller.registration:createAction }