claro_user_registration_form:
    pattern: /register
    defaults: { _controller: ClarolineCoreBundle:Registration:new }
    
claro_user_registration_form_submit:
    pattern: /create
    defaults: { _controller: ClarolineCoreBundle:Registration:create }