claro_user_registration_form:
    pattern: /register
    defaults: { _controller: ClarolineCoreBundle:Registration:new }
    
claro_user_registration_form_submit:
    pattern: /create
    defaults: { _controller: ClarolineCoreBundle:Registration:create }
    
claro_profile_show_edit:
    pattern: /show/edit
    defaults: { _controller: ClarolineCoreBundle:User:showEditProfile }
    
claro_profile_show:
   pattern: show/profile/{id}
   defaults: { _controller: ClarolineCoreBundle:User:showProfile }
    
claro_profile_edit:
    pattern: /edit
    defaults: { _controller: ClarolineCoreBundle:User:editProfile }
    
claro_profile_delete:
   pattern: /delete/{id}
   defaults: { _controller: ClarolineCoreBundle:User:deleteProfile }
