# REST ROUTES (OR CLOSE ENOUGH)

claro_workspace_home:
    pattern: /{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:home }
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_resources:
    pattern: /resource/{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:resources }
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_list:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Workspace:list }
    requirements:
      _method: GET

claro_workspace_create:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Workspace:create }
    requirements:
      _method: POST

claro_workspace_delete:
    pattern: /{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:delete }
    requirements:
      _method: DELETE
      workspaceId: ^(?=.*[1-9].*$)\d*$
    options:
      expose: true

claro_workspace_by_user:
    pattern: /user/{userId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:listWorkspacesByUser }
    options:
      expose: true
    requirements:
      _method: GET
      userId: ^(?=.*[1-9].*$)\d*$

claro_workspace_creation_form:
    pattern: /new/form
    defaults: { _controller: ClarolineCoreBundle:Workspace:creationForm }
    requirements:
      _method: GET

claro_workspace_widgets:
    pattern: /{workspaceId}/widgets
    defaults: { _controller: ClarolineCoreBundle:Workspace:widgets }
    requirements:
      _method: GET

claro_workspace_properties:
    pattern: /{workspaceId}/properties
    defaults: { _controller: ClarolineCoreBundle:Workspace:properties }
    requirements:
      _method: GET

claro_workspace_widget_properties:
  pattern: /{workspaceId}/properties/widget
  defaults: { _controller: ClarolineCoreBundle:Workspace:widgetsProperties }
  requirements:
    _method: GET

claro_workspace_rights:
  pattern: /{workspaceId}/properties/rights
  defaults: { _controller: ClarolineCoreBundle:Workspace:configureRights }
  requirements:
    _method: GET

claro_workspace_resources_rights_form:
  pattern: /{workspaceId}/properties/resources/rights/form
  defaults: { _controller: ClarolineCoreBundle:Workspace:resourcesRightsForm }
  requirements:
    _method: GET

claro_workspace_resources_rigths_edit:
  pattern: /{workspaceId}/properties/resources/rights/edit
  defaults: { _controller: ClarolineCoreBundle:Workspace:editResourcesRights }
  requirements:
    _method: POST

claro_workspace_widget_invertvisible:
  pattern: /{workspaceId}/widget/{widgetId}/baseconfig/{displayConfigId}/invertvisible
  defaults: { _controller: ClarolineCoreBundle:Workspace:invertVisibleWidget }
  requirements:
    _method: POST
  options:
    expose: true

claro_workspace_widget_configuration:
  pattern: /{workspaceId}/widget/{widgetId}/configuration
  defaults: { _controller: ClarolineCoreBundle:Workspace:configureWidget }
  requirements:
    _method: GET
  options:
    expose: true

claro_workspace_agenda:
  pattern: /{workspaceId}/agenda
  defaults: { _controller: ClarolineCoreBundle:Calendar:index }
  
claro_workspace_agenda_add_date:
  pattern: /{workspaceId}/agenda/add
  defaults: { _controller: ClarolineCoreBundle:Calendar:addDate }
  requirements:
    _method: POST




