# REST ROUTES (OR CLOSE ENOUGH)

claro_workspace_home:
    pattern: /{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:home }
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_resources:
    pattern: /resource/{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:resources }
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_list:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Workspace:list }
    requirements:
      _method: GET

claro_workspace_create:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Workspace:create }
    requirements:
      _method: POST

claro_workspace_delete:
    pattern: /{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:delete }
    requirements:
      _method: DELETE
      workspaceId: ^(?=.*[1-9].*$)\d*$
    options:
      expose: true

claro_workspace_by_user:
    pattern: /user/{userId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:listWorkspacesByUser }
    options:
      expose: true
    requirements:
      _method: GET
      userId: ^(?=.*[1-9].*$)\d*$

claro_workspace_creation_form:
    pattern: /new/form
    defaults: { _controller: ClarolineCoreBundle:Workspace:creationForm }
    requirements:
      _method: GET

#OTHERS (maybe they should be removed)

claro_ws_roles_list:
    pattern: /{workspaceId}/roles.{format}
    defaults: { _controller: ClarolineCoreBundle:Workspace:roles }
    options:
      expose: true

claro_ws_user_workspace_id:
   pattern: /user/workspace/id
   defaults: { _controller: ClarolineCoreBundle:Workspace:userWorkspaceId }
   options:
       expose: true

claro_ws_properties:
   pattern: /properties/{workspaceId}
   defaults: { _controller: ClarolineCoreBundle:Workspace:properties }
   options:
      expose: true
