# REST ROUTES (OR CLOSE ENOUGH)

claro_workspace_home:
    pattern: /{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:home }
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_resources:
    pattern: /resource/{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:resources }
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_tools:
    pattern: /{workspaceId}/tools
    defaults: { _controller: ClarolineCoreBundle:Workspace:tools }
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_list:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Workspace:list }
    requirements:
      _method: GET

claro_workspace_create:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Workspace:create }
    requirements:
      _method: POST

claro_workspace_delete:
    pattern: /{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:delete }
    requirements:
      _method: DELETE
      workspaceId: ^(?=.*[1-9].*$)\d*$
    options:
      expose: true

claro_workspace_delete_user:
    pattern: /{workspaceId}/user/{userId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:removeUser, userId:'null' }
    options:
       expose: true
    requirements:
      _method: DELETE
      workspaceId: ^(?=.*[1-9].*$)\d*$
      userId: ^(?=.*[1-9].*$)\d*$

claro_workspace_delete_group:
    pattern: /{workspaceId}/group/{groupId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:removeGroup }
    options:
      expose: true
    requirements:
      _method: DELETE
      workspaceId: ^(?=.*[1-9].*$)\d*$
      groupId: ^(?=.*[1-9].*$)\d*$

claro_workspace_unregistered_users_paginated:
   pattern: /{workspaceId}/users/{offset}/unregistered
   defaults: { _controller: ClarolineCoreBundle:Workspace:paginatedUnregisteredUsers }
   options:
     expose: true
   requirements:
     _method: GET
     workspaceId: ^(?=.*[1-9].*$)\d*$
     #offset 0-9
     offset: ^(?=.*[0-9].*$)\d*$

claro_workspace_unregistered_groups_paginated:
    pattern: /{workspaceId}/groups/{offset}/unregistered
    defaults: { _controller: ClarolineCoreBundle:Workspace:paginatedUnregisteredGroups }
    options:
        expose: true
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$
      #offset 1-9
      offset: ^(?=.*[0-9].*$)\d*$

claro_workspace_registered_users_paginated:
    pattern: /{workspaceId}/users/{offset}/registered
    defaults: { _controller: ClarolineCoreBundle:Workspace:paginatedUsersOfWorkspace }
    options:
        expose: true
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$
      #offset 1-9
      offset: ^(?=.*[0-9].*$)\d*$

claro_workspace_registered_groups_paginated:
    pattern: /{workspaceId}/groups/{offset}/registered
    defaults: { _controller: ClarolineCoreBundle:Workspace:paginatedGroupsOfWorkspace }
    options:
        expose: true
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$
      #offset 1-9
      offset: ^(?=.*[0-9].*$)\d*$

claro_workspace_search_unregistered_users:
    pattern: /{workspaceId}/user/search/{search}/unregistered/{offset}
    defaults: { _controller: ClarolineCoreBundle:Workspace:searchUnregisteredUsers }
    options:
      expose: TRUE
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$
      offset: ^(?=.*[0-9].*$)\d*$

claro_workspace_search_registered_users:
    pattern: /{workspaceId}/user/search/{search}/registered/{offset}
    defaults: { _controller: ClarolineCoreBundle:Workspace:searchRegisteredUsers }
    options:
      expose: TRUE
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$
      offset: ^(?=.*[0-9].*$)\d*$

claro_workspace_search_unregistered_groups:
    pattern: /{workspaceId}/group/search/{search}
    defaults: { _controller: ClarolineCoreBundle:Workspace:searchUnregisteredGroups }
    options:
      expose: TRUE
    requirements:
      _method: GET
      workspaceId: ^(?=.*[0-9].*$)\d*$

claro_workspace_tools_users_management:
    pattern: /{workspaceId}/tools/user_management
    defaults: { _controller: ClarolineCoreBundle:Workspace:usersManagement }
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_tools_user_parameters:
    pattern: /{workspaceId}/tools/user/{userId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:userParameters }
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$
      userId: ^(?=.*[1-9].*$)\d*$
    options:
      expose: TRUE

claro_workspace_unregistered_users_list:
    pattern: /{workspaceId}/tools/users
    defaults: { _controller: ClarolineCoreBundle:Workspace:unregiseredUsersList }
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_tools_groups_management:
    pattern: /{workspaceId}/tools/group_management
    defaults: { _controller: ClarolineCoreBundle:Workspace:groupsManagement }
    requirements:
      _method: GET
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_by_user:
    pattern: /user/{userId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:listWorkspacesByUser }
    options:
      expose: true
    requirements:
      _method: GET
      userId: ^(?=.*[1-9].*$)\d*$

claro_workspace_creation_form:
    pattern: /new/form
    defaults: { _controller: ClarolineCoreBundle:Workspace:creationForm }
    requirements:
      _method: GET

claro_workspace_add_user:
   pattern: /{workspaceId}/user/{userId}
   defaults: { _controller: ClarolineCoreBundle:Workspace:addUser }
   options:
      expose: true
   requirements:
      _method: PUT
      userId: ^(?=.*[1-9].*$)\d*$
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_add_group:
   pattern: /{workspaceId}/group/{groupId}
   defaults: { _controller: ClarolineCoreBundle:Workspace:addGroup }
   options:
      expose: true
   requirements:
      _method: PUT
      groupId: ^(?=.*[1-9].*$)\d*$
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_multiadd_user:
   pattern: /{workspaceId}/add/user
   defaults: { _controller: ClarolineCoreBundle:Workspace:multiAddUser }
   options:
      expose: true
   requirements:
      _method: PUT
      workspaceId: ^(?=.*[1-9].*$)\d*$

claro_workspace_multiadd_group:
   pattern: /{workspaceId}/add/group
   defaults: { _controller: ClarolineCoreBundle:Workspace:multiAddGroup }
   options:
      expose: true
   requirements:
      _method: PUT
      workspaceId: ^(?=.*[1-9].*$)\d*$

#OTHERS (maybe they should be removed)

claro_ws_roles_list:
    pattern: /{workspaceId}/roles.{format}
    defaults: { _controller: ClarolineCoreBundle:Workspace:roles }
    options:
      expose: true

claro_ws_user_workspace_id:
   pattern: /user/workspace/id
   defaults: { _controller: ClarolineCoreBundle:Workspace:userWorkspaceId }
   options:
       expose: true

claro_ws_properties:
   pattern: /properties/{workspaceId}
   defaults: { _controller: ClarolineCoreBundle:Workspace:properties }
   options:
      expose: true
