claro_workspace_new_workspace:
    pattern: /new/form
    defaults: { _controller: ClarolineCoreBundle:Workspace:new }

claro_workspace_create_workspace:
    pattern: /new/create
    defaults: { _controller: ClarolineCoreBundle:Workspace:create }
    requirements:
        _method: POST

claro_workspace_delete_workspace:
    pattern: /delete/{id}
    defaults: { _controller: ClarolineCoreBundle:Workspace:delete }
    
claro_workspace_user_workspace:
    pattern: /list/{userId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:listForUser }
    
claro_workspace_list_all:
    pattern: /list
    defaults: { _controller: ClarolineCoreBundle:Workspace:list }
    
claro_workspace_show_workspace:
    pattern: /show/{id}
    defaults: { _controller: ClarolineCoreBundle:Workspace:show }
    
claro_workspace_register_workspace:
    pattern: /register/{id}
    defaults: { _controller: ClarolineCoreBundle:Workspace:register }
    
claro_workspace_unregister_workspace:
    pattern: /unregister/{id}
    defaults: { _controller: ClarolineCoreBundle:Workspace:unregister }
    
claro_workspace_show_user_list_workspace:
    pattern: /show/list/user/{id}
    defaults: { _controller: ClarolineCoreBundle:Workspace:listUserPerWorkspace }