# REST ROUTES (OR CLOSE ENOUGH)

claro_workspace_list:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Workspace:list }
    requirements:
      _method: GET

claro_workspace_create:
    pattern: /
    defaults: { _controller: ClarolineCoreBundle:Workspace:create }
    requirements:
      _method: POST

claro_workspace_delete:
    pattern: /{workspaceId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:delete }
    requirements:
      _method: DELETE
      workspaceId: ^(?=.*[1-9].*$)\d*$
    options:
      expose: true

claro_workspace_by_user:
    pattern: /user/{userId}
    defaults: { _controller: ClarolineCoreBundle:Workspace:listWorkspacesByUser }
    options:
      expose: true
    requirements:
      _method: GET
      userId: ^(?=.*[1-9].*$)\d*$

claro_workspace_creation_form:
    pattern: /new/form
    defaults: { _controller: ClarolineCoreBundle:Workspace:creationForm }
    requirements:
      _method: GET

claro_workspace_widgets:
    pattern: /{workspaceId}/widgets
    defaults: { _controller: ClarolineCoreBundle:Workspace:widgets }
    requirements:
      _method: GET

claro_workspace_agenda:
  pattern: /{workspaceId}/agenda
  defaults: { _controller: ClarolineCoreBundle:Calendar:index }

claro_workspace_agenda_add_event:
  pattern: /{workspaceId}/agenda/add
  defaults: { _controller: ClarolineCoreBundle:Calendar:addEvent }

claro_workspace_agenda_show:
  pattern: /{workspaceId}/agenda/show
  defaults: { _controller: ClarolineCoreBundle:Calendar:show }
  requirements:
    _method: GET

claro_workspace_agenda_move:
  pattern: /{workspaceId}/agenda/move
  defaults: { _controller: ClarolineCoreBundle:Calendar:move }
  requirements:
    _method: POST

claro_workspace_agenda_delete:
  pattern: /{workspaceId}/agenda/delete
  defaults: { _controller: ClarolineCoreBundle:Calendar:delete }
  requirements:
    _method: POST

claro_workspace_open_tool:
  pattern: /{workspaceId}/open/tool/{toolName}
  defaults: { _controller: ClarolineCoreBundle:Workspace:openTool }
  requirements:
    _method: GET



