tools:
    home:
        widget:
            -
                name: core_resource_logger
                is_visible: true
            -
                name: claroline_rssreader
                is_visible: true
            -
                name: claroline_mywidget1
                is_visible: true
    resource_manager:
        perms:
            ROLE_WS_VISITOR:
                canEdit: '0'
                canOpen: '0'
                canDelete: '0'
                canCopy: '0'
                canExport: '0'
                canCreate: 1
            ROLE_WS_COLLABORATOR:
                canEdit: '0'
                canOpen: '1'
                canDelete: '0'
                canCopy: '0'
                canExport: '1'
                canCreate: 1
            ROLE_WS_MANAGER:
                canEdit: '1'
                canOpen: '1'
                canDelete: '1'
                canCopy: '1'
                canExport: '1'
                canCreate: 1
roles:
    ROLE_WS_VISITOR: visitor
    ROLE_WS_COLLABORATOR: collaborator
    ROLE_WS_MANAGER: manager
creator_role: ROLE_WS_MANAGER
tools_infos:
    home:
        perms:
            - ROLE_WS_VISITOR
            - ROLE_WS_COLLABORATOR
            - ROLE_WS_MANAGER
        translation_key: home
    resource_manager:
        perms:
            - ROLE_WS_COLLABORATOR
            - ROLE_WS_MANAGER
        translation_key: 'resource_manager'
    calendar:
        perms:
            - ROLE_WS_COLLABORATOR
            - ROLE_WS_MANAGER
        translation_key: calendar
    parameters:
        perms:
            - ROLE_WS_MANAGER
        translation_key: parameters
    group_management:
        perms:
            - ROLE_WS_MANAGER
        translation_key: group_management
    user_management:
        perms:
            - ROLE_WS_MANAGER
        translation_key: user_management
name: default
