name: Depôt de ressources
description: Cet espace est un depôt de ressources.
creator_role: ROLE_WS_MANAGER
roles:
    ROLE_WS_VISITOR: 'visitor'
    ROLE_WS_COLLABORATOR: 'collaborator'
    ROLE_WS_MANAGER: 'manager'
tools_permissions:
    resource_manager:
       - 'ROLE_WS_COLLABORATOR'
       - 'ROLE_WS_MANAGER'
       - 'ROLE_WS_VISITOR'
resources_permissions:
    ROLE_WS_VISITOR:
       'canCopy': false
       'canOpen': false
       'canEdit': false
       'canDelete': false
       'canExport': false
       'canCreate': false
    ROLE_WS_COLLABORATOR:
       'canCopy': false
       'canOpen': true
       'canEdit': false
       'canDelete': false
       'canExport': true
       'canCreate': false
    ROLE_WS_MANAGER:
       'canCopy': true
       'canOpen': true
       'canEdit': true
       'canDelete': true
       'canExport': true
       'canCreate': true





