parameters:
    claroline.plugin.validator.class: Claroline\PluginBundle\Service\PluginManager\Validator
    claroline.plugin.file_writer.class: Claroline\PluginBundle\Service\PluginManager\FileWriter
    claroline.plugin.manager.class: Claroline\PluginBundle\Service\PluginManager\Manager
    claroline.plugin.directory: "%kernel.root_dir%/../plugin"
    claroline.plugin.namespaces.config.directory: "%kernel.root_dir%/config/plugin/namespaces"
    claroline.plugin.bundles.config.directory: "%kernel.root_dir%/config/plugin/bundles"

services:
    claroline.plugin.validator:
        class: %claroline.plugin.validator.class%
        arguments: [%claroline.plugin.directory%]
    claroline.plugin.file_writer:
        class: %claroline.plugin.file_writer.class%
        arguments: [%claroline.plugin.namespaces.config.directory%, %claroline.plugin.bundles.config.directory%]
        public: false
    claroline.plugin.manager:
        class: %claroline.plugin.manager.class%
        arguments: [@claroline.plugin.validator, @claroline.plugin.file_writer, @doctrine.orm.entity_manager]