services:
    #controller
    claroline.desktop.desktop_controller:
        class: Claroline\DesktopBundle\Controller\DesktopController
        arguments:
            - "@security.context"
            - "@templating.engine.twig"