services:
  
    claroline.common.history_browser:
        class: Claroline\CoreBundle\Library\Browsing\HistoryBrowser
        scope: request
        arguments:
            - "@request"
            - "@session"
            - "@claroline.config.platform_config_handler"
  
