services:
  
    claroline.common.history_browser:
        class: Claroline\CoreBundle\Browsing\HistoryBrowser
        scope: request
        arguments:
            - "@request"
            - "@session"
            - %context_history_max_size%
  
