services:
    claroline.directory.manager:
        class: Claroline\CoreBundle\Library\Manager\DirectoryManager
        arguments:
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@claroline.security.restricted_owner_right_manager"