parameters:
  
   claroline.files.directory: "%kernel.root_dir%/../files"
  #  prod: "%kernel.root_dir%/../files"
   
services:
    claroline.file.manager:
        class: Claroline\CoreBundle\Library\Manager\FileManager
        arguments:
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@claroline.security.restricted_owner_right_manager"
            - %claroline.files.directory%
            - "@claroline.resource.manager"
            - "@templating"
            
        tags:
           - { name: resource.manager}
