parameters:

   claroline.files.directory: "%kernel.root_dir%/../files"
  #  prod: "%kernel.root_dir%/../files"

services:
    claroline.file.manager:
        class: Claroline\CoreBundle\Controller\FileController
        calls:
           - [ setContainer, [ "@service_container" ] ]
        tags:
           - { name: resource.manager}
