services:
    claroline.common.home_service:
        class: Claroline\CoreBundle\Library\Home\HomeService
        arguments: []

    claroline.twig.home_extension:
        class: Claroline\CoreBundle\Library\Twig\HomeExtension
        arguments: [@translator]
        tags:
            - { name: twig.extension }

