parameters:
  claroline.install.bundle_migrator_class: Claroline\CoreBundle\Service\BundleMigrator

services:
  claroline.install.migration_helper:
    public: false
    class: Claroline\CoreBundle\Library\Migration\MigrationHelper
  
  claroline.install.bundle_migrator:
    public: false
    class: %claroline.install.bundle_migrator_class%
    arguments:
        - "@doctrine.dbal.default_connection"
        - "@claroline.install.migration_helper"
  
  claroline.install.core_installer:
      class: Claroline\CoreBundle\Service\CoreInstaller
      arguments:
        - "@kernel"
        - "@claroline.install.bundle_migrator"