parameters:

    claroline.install.prod_migrations_directory: Migrations
    claroline.install.test_migrations_directory: Tests/Stub/Migrations
    claroline.install.include_test_migrations: false # see config_test.yml
    claroline.plugin.directory: "%kernel.root_dir%/../src/plugin"
    claroline.plugin.namespaces_config_file: "%kernel.root_dir%/config/local/plugin/namespaces"
    claroline.plugin.bundles_config_file: "%kernel.root_dir%/config/local/plugin/bundles"
    claroline.plugin.routing_config_file: "%kernel.root_dir%/config/local/plugin/routing.yml"

services:

    claroline.install.core_installer:
        class: Claroline\CoreBundle\Library\Installation\Core\Installer
        arguments:
            - "@kernel"
            - "@claroline.install.bundle_migrator"

    claroline.install.bundle_migrator:
        public: false
        class: Claroline\CoreBundle\Library\Installation\BundleMigrator
        arguments:
            - "@claroline.install.migration_builder"

    claroline.install.migration_builder:
        class: Claroline\CoreBundle\Library\Installation\MigrationBuilder
        arguments:
            - "@doctrine.dbal.default_connection"
            - "@claroline.install.migration_helper"
            - %claroline.install.prod_migrations_directory%
            - %claroline.install.test_migrations_directory%
            - %claroline.install.include_test_migrations%

    claroline.install.migration_helper:
        public: false
        class: Claroline\CoreBundle\Library\Installation\MigrationHelper

    claroline.plugin.installer:
        class: Claroline\CoreBundle\Library\Installation\Plugin\Installer
        arguments:
            - "@claroline.plugin.loader"
            - "@claroline.plugin.validator"
            - "@claroline.plugin.migrator"
            - "@claroline.plugin.recorder"
            - "@kernel"

    claroline.plugin.loader:
        class: Claroline\CoreBundle\Library\Installation\Plugin\Loader
        arguments:
            - %claroline.plugin.directory%

    claroline.plugin.validator:
        class: Claroline\CoreBundle\Library\Installation\Plugin\Validator
        arguments:
              - routing: "@claroline.plugin.routing_checker"
                config: "@claroline.plugin.config_checker"

    claroline.plugin.routing_checker:
        class: Claroline\CoreBundle\Library\Installation\Plugin\RoutingChecker
        arguments:
            - "@router"
            - "@symfony.yaml"
            - "%kernel.root_dir%/config/local/plugin/routing.yml"

    claroline.plugin.config_checker:
        class: Claroline\CoreBundle\Library\Installation\Plugin\ConfigurationChecker
        arguments:
            - "@symfony.yaml"
            - "@doctrine.orm.entity_manager"

    claroline.plugin.migrator:
        class: Claroline\CoreBundle\Library\Installation\Plugin\Migrator
        arguments:
            - "@claroline.install.bundle_migrator"

    claroline.plugin.recorder:
        class: Claroline\CoreBundle\Library\Installation\Plugin\Recorder
        arguments:
            - "@claroline.plugin.recorder_configuration_file_writer"
            - "@claroline.plugin.recorder_database_writer"

    claroline.plugin.recorder_configuration_file_writer:
        class: Claroline\CoreBundle\Library\Installation\Plugin\ConfigurationFileWriter
        arguments:
            - %claroline.plugin.namespaces_config_file%
            - %claroline.plugin.bundles_config_file%
            - %claroline.plugin.routing_config_file%
            - "@symfony.yaml"

    claroline.plugin.recorder_database_writer:
        class: Claroline\CoreBundle\Library\Installation\Plugin\DatabaseWriter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@claroline.resource.icon_creator"
            - "@filesystem"
            - %kernel.root_dir%

    claroline.installation.requirements_checker:
        class: Claroline\CoreBundle\Library\Installation\RequirementsChecker
        arguments:
            - %kernel.root_dir%

    # symfony class used as service argument
    symfony.yaml:
        class: Symfony\Component\Yaml\Yaml
        public: false