services:

    claroline.listener.user_password_encoder:
        class: Claroline\CoreBundle\Listener\UserPasswordEncoder
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: doctrine.event_subscriber, event: prePersist}
            - { name: doctrine.event_subscriber, event: preUpdate}

    claroline.listener.locale_setter:
        class: Claroline\CoreBundle\Listener\LocaleSetter
        arguments: ["@claroline.config.platform_config_handler"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    claroline.listener.resource_mode_selector:
        class: Claroline\CoreBundle\Listener\Resource\ModeSelector
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    claroline.listener.ajax_authentication:
        class: Claroline\CoreBundle\Listener\AjaxAuthenticationListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onCoreException, priority: 1 }

    claroline.listener.resource_extender:
        class: Claroline\CoreBundle\Listener\ResourceExtender
        tags:
            - { name: doctrine.event_subscriber, event: loadClassMetadata, connection: default}

    claroline.listener.directory_listener:
        class: Claroline\CoreBundle\Listener\Resource\DirectoryListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: create_form_directory, method: onCreateForm }
            - { name: kernel.event_listener, event: create_directory, method: onCreate }
            - { name: kernel.event_listener, event: open_directory, method: onOpen }
            - { name: kernel.event_listener, event: resource_directory_to_template, method: onExportTemplate }
            - { name: kernel.event_listener, event: resource_directory_from_template, method: onImportTemplate }

    claroline.listener.file_listener:
        class: Claroline\CoreBundle\Listener\Resource\FileListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: create_form_file, method: onCreateForm }
            - { name: kernel.event_listener, event: create_file, method: onCreate }
            - { name: kernel.event_listener, event: delete_file, method: onDelete }
            - { name: kernel.event_listener, event: copy_file, method: onCopy }
            - { name: kernel.event_listener, event: download_file, method: onDownload }
            - { name: kernel.event_listener, event: open_file, method: onOpen }
            - { name: kernel.event_listener, event: resource_file_to_template, method: onExportTemplate }
            - { name: kernel.event_listener, event: resource_file_from_template, method: onImportTemplate }

    claroline.listener.text_listener:
        class: Claroline\CoreBundle\Listener\Resource\TextListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: create_form_text, method: onCreateForm }
            - { name: kernel.event_listener, event: create_text, method: onCreate }
            - { name: kernel.event_listener, event: open_text, method: onOpen }
            - { name: kernel.event_listener, event: delete_text, method: onDelete }
            - { name: kernel.event_listener, event: copy_text, method: onCopy }
            - { name: kernel.event_listener, event: resource_text_to_template, method: onExportTemplate }
            - { name: kernel.event_listener, event: resource_text_from_template, method: onImportTemplate }

    claroline.listener.activity_listener:
        class: Claroline\CoreBundle\Listener\Resource\ActivityListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: create_form_activity, method: onCreateForm }
            - { name: kernel.event_listener, event: create_activity, method: onCreate }
            - { name: kernel.event_listener, event: open_activity, method: onOpen }
            - { name: kernel.event_listener, event: copy_activity, method: onCopy }
            - { name: kernel.event_listener, event: delete_activity, method: onDelete }
            - { name: kernel.event_listener, event: resource_activity_to_template, method: onExportTemplate }
            - { name: kernel.event_listener, event: resource_activity_from_template, method: onImportTemplate }

    claroline.listener.workspace_logger:
        class: Claroline\CoreBundle\Listener\WorkspaceLogListener
        calls:
           - [setContainer, ["@service_container"]]
        tags:
           - { name: kernel.event_listener, event: log_workspace_access, method: onLogWorkspaceAccess }

    claroline.listener.logger:
        class: Claroline\CoreBundle\Listener\LogListener
        calls:
           - [setContainer, ["@service_container"]]
        tags:
           - { name: kernel.event_listener, event: log_resource, method: onLogResource }

    claroline.listener.core_resource_logger:
      class:  Claroline\CoreBundle\Listener\CoreResourceLogListener
      calls:
        - [setContainer, ["@service_container"]]
      tags:
        - { name: kernel.event_listener, event: widget_core_resource_logger_workspace, method: onWorkspaceDisplay }
        - { name: kernel.event_listener, event: widget_core_resource_logger_desktop, method: onDesktopDisplay }


    claroline.listener.resource_tool:
      class: Claroline\CoreBundle\Listener\ToolListener
      calls:
        - [setContainer, ["@service_container"]]
      tags:
        - { name: kernel.event_listener, event: open_tool_workspace_resource_manager, method: onDisplayWorkspaceResouceManager }
        - { name: kernel.event_listener, event: open_tool_workspace_parameters, method: onDisplayWorkspaceParameters }
        - { name: kernel.event_listener, event: open_tool_workspace_user_management, method: onDisplayWorkspaceUserManagement }
        - { name: kernel.event_listener, event: open_tool_workspace_group_management, method: onDisplayWorkspaceGroupManagement }
        - { name: kernel.event_listener, event: open_tool_workspace_home, method: onDisplayWorkspaceHome }
        - { name: kernel.event_listener, event: open_tool_workspace_calendar, method: onDisplayWorkspaceCalendar }
        - { name: kernel.event_listener, event: open_tool_desktop_resource_manager, method: onDisplayDesktopResourceManager }
        - { name: kernel.event_listener, event: open_tool_desktop_home, method: onDisplayDesktopHome }
        - { name: kernel.event_listener, event: open_tool_desktop_parameters, method: onDisplayDesktopParameters }
        - { name: kernel.event_listener, event: open_tool_desktop_calendar, method: onDisplayDesktopCalendar }
        - { name: kernel.event_listener, event: tool_home_to_template, method: onExportHome }
        - { name: kernel.event_listener, event: tool_home_from_template, method: onImportHome }
        - { name: kernel.event_listener, event: tool_resource_manager_to_template, method: onExportResource }
        - { name: kernel.event_listener, event: tool_resource_manager_from_template, method: onImportResource }