services:

    claroline.resource.icon_creator:
        class: Claroline\CoreBundle\Library\Resource\IconCreator
        arguments:
          - "@service_container"

    claroline.resource.manager:
        class: Claroline\CoreBundle\Library\Resource\Manager
        arguments:
          - "@service_container"

    claroline.resource.exporter:
        class: Claroline\CoreBundle\Library\Resource\Exporter
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@event_dispatcher"
          - "@claroline.resource.utilities"
          - "@security.context"

    claroline.resource.utilities:
         class: Claroline\CoreBundle\Library\Resource\Utilities

    claroline.resource.converter:
         class: Claroline\CoreBundle\Library\Resource\Converter
         arguments:
           - "@doctrine.orm.entity_manager"
           - "@claroline.security.utilities"
           - "@translator"

    claroline.resource.mode_extension:
        class: Claroline\CoreBundle\Library\Twig\ResourceModeExtension
        arguments:
          - "@router"
        tags:
            - { name: twig.extension }

