services:
    claroline.resource.manager:
        class: Claroline\CoreBundle\Library\Manager\ResourceManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@claroline.security.restricted_owner_right_manager"