parameters:
   # next lines are overriden by app config_test.yml in test environment
   claroline.files.directory: "%kernel.root_dir%/../files"
   claroline.thumbnails.directory: "%kernel.root_dir%/../web/thumbnails"

services:

    claroline.icon.creator:
        class: Claroline\CoreBundle\Library\Resource\IconCreator
        arguments:
          - %claroline.files.directory%
          - "@service_container"

    claroline.resource.manager:
        class: Claroline\CoreBundle\Library\Resource\Manager
        arguments:
          - "@service_container"