parameters:
   # next lines are overriden by app config_test.yml in test environment
   claroline.files.directory: "%kernel.root_dir%/../files"
   claroline.thumbnails.directory: "%kernel.root_dir%/../web/thumbnails"

services:

    claroline.resource.icon_creator:
        class: Claroline\CoreBundle\Library\Resource\IconCreator
        arguments:
          - %claroline.files.directory%
          - "@service_container"

    claroline.resource.manager:
        class: Claroline\CoreBundle\Library\Resource\Manager
        arguments:
          - "@service_container"

    claroline.resource.exporter:
        class: Claroline\CoreBundle\Library\Resource\Exporter
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@event_dispatcher"
          - "@claroline.resource.utilities"
          - "@security.context"

    claroline.resource.utilities:
         class: Claroline\CoreBundle\Library\Resource\Utilities

    claroline.resource.converter:
         class: Claroline\CoreBundle\Library\Resource\Converter
         arguments:
           - "@doctrine.orm.entity_manager"
           - "@claroline.security.utilities"

    claroline.resource.mode_extension:
        class: Claroline\CoreBundle\Library\Twig\ResourceModeExtension
        arguments:
          - "@router"
        tags:
            - { name: twig.extension }

