parameters:
   # next line is overriden by app config_test.yml in test environment
   claroline.files.directory: "%kernel.root_dir%/../files"
   claroline.resource.img: "%kernel.root_dir%/../src/core/Claroline/CoreBundle/Resources/public/images/resources/icon"

services:

    claroline.text.manager:
        class: Claroline\CoreBundle\Resource\TextManager
        arguments:
          - "@service_container"
        tags:
           - { name: resource.controller }

    claroline.thumbnail.creator:
        class: Claroline\CoreBundle\Library\Resource\ThumbnailGenerator
        arguments:
          - %claroline.files.directory%

    claroline.resource.manager:
        class: Claroline\CoreBundle\Library\Resource\Manager
        arguments:
          - "@service_container"