services:
  
    claroline.security.admin_voter:
        class: Claroline\CoreBundle\Library\Security\Voter\AdministratorVoter
        tags:
            -  { name: security.voter }
            
    claroline.security.right_manager.delegate.entity:
        class: Claroline\CoreBundle\Library\Security\RightManager\Delegate\EntityDelegate
    
    claroline.security.right_manager.delegate.class:
        class: Claroline\CoreBundle\Library\Security\RightManager\Delegate\ClassDelegate
    
    claroline.security.right_manager.delegate.user:
        class: Claroline\CoreBundle\Library\Security\RightManager\Delegate\UserDelegate
        arguments:
            - "@doctrine.orm.entity_manager"
    
    claroline.security.right_manager.delegate.role:
        class: Claroline\CoreBundle\Library\Security\RightManager\Delegate\RoleDelegate
        arguments:
            - "@doctrine.orm.entity_manager"
    
    claroline.security.right_manager.strategy_chooser:
        class: Claroline\CoreBundle\Library\Security\RightManager\Delegate\StrategyChooser
        arguments:
            - "@claroline.security.right_manager.delegate.entity"
            - "@claroline.security.right_manager.delegate.class"
            - "@claroline.security.right_manager.delegate.user"
            - "@claroline.security.right_manager.delegate.role"
    
    claroline.security.right_manager:
        class: Claroline\CoreBundle\Library\Security\RightManager\RightManager
        arguments:
            - "@security.acl.provider"
            - "@claroline.security.right_manager.strategy_chooser"
    
    claroline.security.restricted_owner_right_manager:
        class: Claroline\CoreBundle\Library\Security\RightManager\RestrictedOwnerRightManager
        arguments:
            - "@claroline.security.right_manager"
