services:

    claroline.user.creator:
        class: Claroline\CoreBundle\Library\User\Creator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@translator"
            - "@claroline.config.platform_config_handler"
            - "@claroline.workspace.creator"
            - %claroline.workspace_template.directory%
