services:

    claroline.utilities.lipsum_generator:
        class: Claroline\CoreBundle\Library\Utilities\LipsumGenerator

    claroline.utilities.paginator_parser:
        class: Claroline\CoreBundle\Library\Utilities\PaginatorParser

    claroline.utilities.controller_name_parser:
        class: %controller_name_converter.class%
        arguments:
          - "@kernel"