services:

    claroline.utilities.lipsum_generator:
        class: Claroline\CoreBundle\Library\Utilities\LipsumGenerator

    claroline.utilities.paginator_parser:
        class: Claroline\CoreBundle\Library\Utilities\PaginatorParser

    claroline.utilities.thumbnail_creator:
        class: Claroline\CoreBundle\Library\Utilities\ThumbnailCreator
        arguments:
          - "%kernel.root_dir%"
          - "%claroline.thumbnails.directory%"
          - "@claroline.resource.utilities"

    claroline.utilities.controller_name_parser:
        class: %controller_name_converter.class%
        arguments:
          - "@kernel"

    claroline.utilities.caml_case_to_underscore__filter_extension:
        class: Claroline\CoreBundle\Library\Twig\CamlCaseToUnderscoreFilterExtension
        tags:
            - { name: twig.extension }