services:

    claroline.workspace.creator:
        class: Claroline\CoreBundle\Library\Workspace\Creator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@claroline.security.right_manager"

    claroline.workspace.toolinstance_manager:
        class: Claroline\CoreBundle\Library\Manager\ToolInstanceManager
        arguments:    
            - "@doctrine.orm.entity_manager"
            - "@claroline.security.right_manager"
            - Claroline\CoreBundle\Entity\ToolInstance
