services:

    claroline.workspace.creator:
        class: Claroline\CoreBundle\Library\Workspace\Creator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@claroline.security.right_manager"

parameters:
    claroline.workspace_template.directory: "%kernel.root_dir%/../src/core/Claroline/CoreBundle/Resources/config/workspace/"
