
services:

    claroline.workspace.creator:
        class: Claroline\CoreBundle\Library\Workspace\Creator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@claroline.resource.manager"
            - "@event_dispatcher"
            - "@translator"

    claroline.workspace.exporter:
        class: Claroline\CoreBundle\Library\Workspace\Exporter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "%claroline.param.templates_directory%"

parameters:
    claroline.workspace_template.directory: "%kernel.root_dir%/../templates/"

