
services:

    claroline.workspace.creator:
        class: Claroline\CoreBundle\Library\Workspace\Creator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@claroline.security.right_manager"
            - "@event_dispatcher"

    claroline.workspace.exporter:
        class: Claroline\CoreBundle\Library\Workspace\Exporter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"

parameters:
    claroline.workspace_template.directory: "%kernel.root_dir%/../src/core/Claroline/CoreBundle/Resources/config/workspace/"
