services:

    claroline.workspace.creator:
        class: Claroline\CoreBundle\Library\Workspace\Creator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@claroline.security.right_manager"
