claro_workspace_new_workspace:
    pattern: /workspaces/new
    defaults: { _controller: ClarolineWorkspaceBundle:Workspace:new }
    requirements:
        _method:  GET

claro_workspace_create_workspace:
    pattern: /workspace
    defaults: { _controller: ClarolineWorkspaceBundle:Workspace:create }
    requirements:
        _method:  POST
        
claro_workspace_delete_workspace:
  pattern: /workspace/{id}/delete
  defaults: { _controller: ClarolineWorkspaceBundle:Workspace:delete }
  requirements:
        _method:  POST