claro_user_registration_form:
    pattern: /register
    defaults: { _controller: claroline.user.registration_controller:newAction }
    
claro_user_registration_form_submit:
    pattern: /create
    defaults: { _controller: claroline.user.registration_controller:createAction }