services:
  
    claroline.user.manager:
        class: Claroline\UserBundle\Manager\UserManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@validator"
            - "@security.encoder_factory"
            - "@claroline.security.role_manager"
            
    # controllers
    
    claroline.user.registration_controller:
        class: Claroline\UserBundle\Controller\RegistrationController
        scope: request
        arguments:
            - "@request"
            - "@security.context"
            - "@form.factory"
            - "@templating.engine.twig"
            - "@translator"
            - "@claroline.user.manager"
            - %allow_self_registration%