claro_workspace_new_workspace:
    pattern: /workspaces/new
    defaults: { _controller: claroline.workspace.workspace_controller:newAction }
    requirements:
        _method: GET

claro_workspace_create_workspace:
    pattern: /workspace
    defaults: { _controller: claroline.workspace.workspace_controller:createAction }
    requirements:
        _method: POST
        
claro_workspace_delete_workspace:
    pattern: /workspace/{id}/delete
    defaults: { _controller: claroline.workspace.workspace_controller:deleteAction }
    requirements:
        _method: POST