services:
  
    claroline.workspace.user_manager:
        class: Claroline\WorkspaceBundle\Manager\UserManager
        arguments:    
            - "@doctrine.orm.entity_manager"
            - "@claroline.security.right_manager"
  
    claroline.workspace.workspace_manager:
        class: Claroline\WorkspaceBundle\Service\Manager\WorkspaceManager
        arguments:    
            - "@doctrine.orm.entity_manager"
            - Claroline\WorkspaceBundle\Entity\Workspace
        public: false
    claroline.workspace.acl_workspace_manager:
        class: Claroline\WorkspaceBundle\Service\Manager\ACLWorkspaceManager
        arguments:    
            - "@claroline.workspace.workspace_manager"
            - "@security.context"
            - "@security.acl.provider"
    # controller
    claroline.workspace.workspace_controller:
        class: Claroline\WorkspaceBundle\Controller\WorkspaceController
        scope: request
        arguments:
            - "@request"
            - "@session"
            - "@security.context"
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@form.factory"
            - "@templating.engine.twig"
            - "@claroline.workspace.user_manager"
            - "@claroline.common.history_browser"