services:
  
    claroline.workspace.user_manager:
        class: Claroline\WorkspaceBundle\Manager\UserManager
        arguments:    
            - "@doctrine.orm.entity_manager"
            - "@claroline.security.right_manager"
                        
    claroline.workspace.toolinstance_manager:
        class: Claroline\WorkspaceBundle\Manager\ToolInstanceManager
        arguments:    
            - "@doctrine.orm.entity_manager"
            - Claroline\PluginBundle\Entity\ToolInstance
  
    # controller
    claroline.workspace.workspace_controller:
        class: Claroline\WorkspaceBundle\Controller\WorkspaceController
        scope: request
        arguments:
            - "@request"
            - "@session"
            - "@security.context"
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@form.factory"
            - "@templating.engine.twig"
            - "@claroline.workspace.user_manager"
            - "@claroline.common.history_browser"
            